### ISSUE TITLE
.gitsubtrees status?

### ISSUE THREAD

**Issue by stela5** [tdd/git-stree#11]
Great project!  Any status update on adding the **.gitsubtrees** / **git stree sync** functionality mentioned on https://medium.com/@porteneuve/mastering-git-subtrees-943d29a798ec ?

**Comment by tdd** [comment]
Hey!

I'm unfortunately underwater these days with many, many regular-job 
projects that need to move forward.  git stree work remains very high on 
my not-regular-job list, so expect some good work between now and late 
June, but unfortunately not sooner than that.

-- 
Christophe Porteneuve
Founder & CTO, Delicious Insights
christophe@delicious-insights.com
+33 662 059 656

**Comment by stela5** [comment]
No problem, I totally understand.  Keep up the great work!
