### ISSUE TITLE
stree push after pull

### ISSUE THREAD

**Issue by pedroteixeira** [tdd/git-stree#13]
Hi, I modified a subtree, did a pull, when I try a push I get:

✔︎ No local commits found for subtree 'js-commons' since latest sync

But I do have local commits not in the remove. Any idea on how to fix this? (perhaps force it get another sync ref?)

thanks.

**Comment by pedroteixeira** [comment]
on line:
`git push --quiet &&`

I guess you're missing the branch name on the push, right? I get warnings about the unset push.default

**Comment by tdd** [comment]
Hey Pedro,

Good catch! I've always defined `push.default` (to `upstream`), so forgot unqualified push would result in warning. Will fix!

As for your other situation, I'll try and see whether I can reproduce this on my side. If not, I'll need a full reproducible scenario.
