### ISSUE TITLE
Does stree work on Windows computer?

### ISSUE THREAD

**Issue by byzheng** [tdd/git-stree#15]
Looks stree is very interesting project for me. I try to use on Windows 7 using git bash (1.9.5), but get an error messages to run the demo command (https://medium.com/@porteneuve/mastering-git-subtrees-943d29a798ec)

    git stree add demo -P vendor/plugins/demo ../remotes/plugin master

    C:\Program Files (x86)\Git/libexec/git-core\git-stree: line 32: conditional binary operator expected
    C:\Program Files (x86)\Git/libexec/git-core\git-stree: line 32: syntax error near `=~'
    C:\Program Files (x86)\Git/libexec/git-core\git-stree: line 32: `tty -s <&1 && [[ "$TERM" =~ color ]] &&      is_tty=true || is_tty=false'

**Comment by tdd** [comment]
Hey there,

Yes, this is a known issue: #6 — Will do soon!
