### ISSUE TITLE
Feature request: git stree format-patch

### ISSUE THREAD

**Issue by kergoth** [tdd/git-stree#21]
I think there would be value in having a way to export a patch series, or split off a local branch, of the changes to be pushed to upstream, rather than pushing to it directly, to handle cases where you don't have push access to the upstream. At the very least, if not this, then at least have a way to push to a different url, in case you added the remote from upstream, but now want to create a fork later on. E.g. an equivalent to git remote set-url would be nice, to avoid having to directly modify .git/config.

**Comment by tdd** [comment]
Hey Christopher,

Yes, asymetric pull/push for pull-request-style work. It's been suggested in #14 already. I'll mark this as a duplicate if you don't mind.
