### ISSUE TITLE
Mixing stree with git subtree

### ISSUE THREAD

**Issue by Rask** [tdd/git-stree#25]
Hello!

Not an issue as is, but I was wondering whether it is possible to mix and match `git subtree` and `git stree` inside the same project where multiple developers are working with varying development environments?

If I use `git stree` and someone else on my team uses `git subtree` (or some more manual approach) would there be any conflicts that could break the system?

As I understand it `git subtree` and `git stree` are wrappers for the same base system, with varying ways for repo management and cli commands. Is this correct?

**Comment by tdd** [comment]
Hey there!

Actually `git subtree` does things its very own way, and demands anything it handles be injected in the codebase through an original `git subtree add`, then maintained the same way. It's a silo.  Most notably, it completely relies on merge commits as add/pull points to work, which `git stree` specifically avoids, as we consider it to be graph pollution.

So unfortunately no, you won't be able to mix and match `git subtree` with any other solution out there, including native, bare-bones subtree management.  Sorry :disappointed:

**Comment by Rask** [comment]
Alrighty. I'll try to convince my team members to get on git stree then. Thanks for clarifying. :)
