### ISSUE TITLE
git stree pull borks on too-large squash logs (> 4K)

### ISSUE THREAD

**Issue by wotwot** [tdd/git-stree#5]
the attempted commit breaks with
`/usr/local/bin/git-stree: line 296: /usr/lib/git-core/git: Argument
list too long`
`✔︎ STree 'logfromblammo' pulled, updates committed.`
upon retrying the git stree pull, the entire remote commit log is taken again, squashed and used as commit message.

**Comment by tdd** [comment]
Also wanted for this:

* Fix sync ID
* Allow large pulls (the core, OP's issue)
* Allow log size customization through optional `--log=` (default to 20, much like `git merge --log`)

**Comment by yyyledu** [comment]
The git merge options --squash --log=2, as used in this commit [0c2879c](https://github.com/deliciousinsights/git-stree/commit/0c2879c0a983e136dc8818a17ff5084e0fd54816), don't seem to work together. The --log=2 works when not combined with --squash. Examining the .git/SQUASH_MSG file shows that the entire remote log is taken again as in the original report by 
wotwot. Tested with git version 1.7.11.3 and 1.7.12.4. In what versions is this fix confirmed to work?
