### ISSUE TITLE
Make a release.

### ISSUE THREAD

**Issue by a1russell** [tdd/git-stree#7]
I'd like to make git-stree installable via Homebrew and have already created a [git-stree pull request in the head-only tap](https://github.com/Homebrew/homebrew-head-only/pull/104). Making a release (maybe 0.1.0 to follow [semantic versioning](http://semver.org/)) would allow creation of a true Homebrew formula.

**Comment by tdd** [comment]
Hey Adam,

That's a great idea, thanks!

I've got a few things to fix but can def tag a release so you switch 
your formula.

I'm super busy this weekend but will make this happen within 2-3 days.

Cheers,

-- 
Christophe Porteneuve
Founder & CTO, Delicious Insights
christophe@delicious-insights.com
+33 662 059 656

**Comment by tdd** [comment]
Hey Adam, tagged v0.4.0 for you.

Cheers!

**Comment by tdd** [comment]
Hey Adam,

Training ppl on Git right here, tried `brew install git-stree`, works a charm :tada: well done you :+1:

**Comment by a1russell** [comment]
Awesome; glad to be of help!
