### ISSUE TITLE
Make 'git stree forget' require confirmation, especially if a specific subtree is on the command line

### ISSUE THREAD

**Issue by werdnum** [tdd/git-stree#9]
I accidentally blew away all my subtrees by typing git stree forget my-subtree-name. This is confusing and made me lose a lot of work.

Also, it would be nice if git stree forget / git stree rm had a documented way to get the subtrees back.

**Comment by tdd** [comment]
Hey!

Your subtrees' code is not lost, only their configuration. That being said, I agree `forget` should detect when extra args are passed, particularly subtree names, and refuse to work then. A prompt confirmation (unless `-f`) would also be nice.

Keeping this issue open so we implement this.
